# fly.toml app configuration file generated for hello-go-wfdyuq on 2024-11-03T09:52:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hello-go-wfdyuq'
primary_region = 'den'

[build]
  [build.args]
    GO_VERSION = '1.23.2'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
